import type { Metadata } from "next";
import "./globals.css";
import ProtectedRoutes from "@/components/protectedRoutes";

import { Urbanist, Open_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Cooperative App",
  description: "Generated by create next app",
};

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const opensans = Open_Sans({
  variable: "--font-opensans",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${urbanist.variable} ${opensans.variable}`}>
      <body className="bg-gradient-to-br from-[#dad7d7] via-[#dad7d7] to-[#f8d752c9]">
        <ProtectedRoutes>{children}</ProtectedRoutes>
      </body>
    </html>
  );
}
